app:
  name: API Gateway
  routes:
    orders:
      uri: https://service-commandes.internal
      target-application: Service commandes
    payments:
      uri: https://paiements.internal
      target-application: Paiements
    customers:
      uri: https://base-clients.internal
      target-application: Base clients
  callers:
    - Portail client
